PropertyPosting/Controllers/MvcControllers/Administrator/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PropertyPosting.Controllers.Base;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class HomeController : BaseController
    {
        public HomeController(IMapper mapper) : base(mapper)
        {
        }

        public override ActionResult Index()
        {
            return View("~/Views/Administrator/Home/Index.cshtml");
        }

        public ActionResult PostHome()
        {
            return View();
        }
        public override ActionResult Details(long id)
        {
            throw new NotImplementedException();
        }
    }
}

PropertyPosting/Controllers/MvcControllers/Administrator/PostEntertainmentController.cs
using AutoMapper;
using PropertyPosting.Controllers.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class PostEntertainmentController : BaseController
    {
        public PostEntertainmentController(IMapper mapper) :base(mapper)
        {

        }
        public override ActionResult Details(long id)
        {
            throw new NotImplementedException();
        }


        public override ActionResult Index()
        {
            return View();
        }
    }
}

PropertyPosting/Controllers/MvcControllers/Administrator/PostLandController.cs
using AutoMapper;
using PropertyPosting.Controllers.Base;
using System.Web.Mvc;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class PostLandController : BaseController
    {
        private readonly IMapper _mapper;
        public PostLandController(IMapper mapper): base(mapper)
        {
            _mapper = mapper;
        }
        public override ActionResult Details(long id)
        {

            return View();
        }

        public ActionResult Create()
        {

            return View();
        }

        public override ActionResult Index()
        {
            return View();
        }
    }
}

PropertyPosting/Controllers/MvcControllers/Administrator/PostTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PropertyPosting.Controllers.Base;
using PropertyPosting.Models.Domains;
using PropertyPosting.Models.Repository;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class PostTypeController : BaseController
    {
        private readonly IRepository<PostType> _postTypeService;
        private readonly IMapper _mapper;

        public PostTypeController(IMapper mapper, IRepository<PostType> postTypeService) : base(mapper)
        {
            _mapper = mapper;
            _postTypeService = postTypeService;
        }

        public override ActionResult Index()
        {
            var postTypes = _postTypeService.GetAll();
            return View("~/Views/Administrator/PostType/Index.cshtml", postTypes);
        }

        public ActionResult Add()
        {
            return View("~/Views/Administrator/PostType/Create.cshtml");
        }

        [HttpPost]
        public ActionResult Add(PostType postType)
        {
            ModelState.Remove("Id");
            if (!ModelState.IsValid)
                return View("~/Views/Administrator/PostType/Create.cshtml", postType);

            if (postType.Id > 0)
            {
                var postTypeUpdate = _mapper.Map<PostType>(postType);
                _postTypeService.Update(postTypeUpdate);
            }
            else
            {
                _postTypeService.Insert(postType);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var postType = _postTypeService.GetById(id);
            if (postType != null)
            {
                _postTypeService.Delete(postType);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var postType = _postTypeService.GetById(id);
            return View("~/Views/Administrator/PostType/Create.cshtml", postType);
        }

        public override ActionResult Details(long id)
        {
            throw new NotImplementedException();
        }
    }
}

PropertyPosting/Views/Administrator/Layout/AdministratorLayout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> ModularAdmin - Free Dashboard Theme | HTML Version </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon.png">
    <title>Matrix Template - The Ultimate Multipurpose admin template</title>
    <!-- Custom CSS -->

    @Styles.Render("~/assets/libs/flot/css/float-chart.css")
    <!-- Custom CSS -->
    @Styles.Render("~/dist/css/style.min.css")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="~/assets/libs/datatables/media/css/jquery.dataTables.min.css" rel="stylesheet" />

    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jquery.signalR-2.3.0.min.js")
    <!--Reference the autogenerated SignalR hub script. -->
    @Scripts.Render("~/signalr/hubs")

</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        @RenderPage("~/Views/Administrator/Layout/_Header.cshtml")
        @RenderPage("~/Views/Administrator/Layout/_Sidebar.cshtml")
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">@ViewBag.Title</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Library</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->

            @RenderBody()
            @RenderPage("~/Views/Administrator/Layout/_Footer.cshtml")
            
        </div>

    </div>

    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <!-- Bootstrap tether Core JavaScript -->

    @Scripts.Render("~/assets/libs/popper-js/dist/umd/popper.min.js")

    @Scripts.Render("~/assets/libs/bootstrap/dist/js/bootstrap.min.js")
    @Scripts.Render("~/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js")
    @Scripts.Render("~/assets/extra-libs/sparkline/sparkline.js")
    <!--Wave Effects -->
    @Scripts.Render("~/dist/js/waves.js")
    <!--Menu sidebar -->
    @Scripts.Render("~/dist/js/sidebarmenu.js")
    <!--Custom JavaScript -->
    @Scripts.Render("~/dist/js/custom.min.js")
    <!--This page JavaScript -->
    <!-- <script src="../../dist/js/pages/dashboards/dashboard1.js"></script> -->
    <!-- Charts js Files -->
    @Scripts.Render("~/assets/libs/datatables/media/js/jquery.dataTables.min.js")
    @Scripts.Render("~/assets/libs/flot/excanvas.js")
    @Scripts.Render("~/assets/libs/flot/jquery.flot.js")
    @Scripts.Render("~/assets/libs/flot/jquery.flot.pie.js")
    @Scripts.Render("~/assets/libs/flot/jquery.flot.time.js")
    @Scripts.Render("~/assets/libs/flot/jquery.flot.stack.js")
    @Scripts.Render("~/assets/libs/flot/jquery.flot.crosshair.js")
    @Scripts.Render("~/assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js")
    @Scripts.Render("~/dist/js/pages/chart/chart-page-init.js")
</body>
</html>

PropertyPosting/Views/Administrator/Layout/_Footer.cshtml
<!-- footer -->
<!-- ============================================================== -->
<footer class="footer text-center">
    All Rights Reserved by Matrix-admin. Designed and Developed by <a href="https://wrappixel.com">WrapPixel</a>.
</footer>
<!-- ============================================================== -->
<!-- End footer -->
<!-- ============================================================== -->

PropertyPosting/Views/Administrator/Layout/_Header.cshtml
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="index.html">
                <!-- Logo icon -->
                <b class="logo-icon p-l-10">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="../../assets/images/logo-icon.png" alt="homepage" class="light-logo" />

                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                    <!-- dark Logo text -->
                    <img src="../../assets/images/logo-text.png" alt="homepage" class="light-logo" />

                </span>
                <!-- Logo icon -->
                <!-- <b class="logo-icon"> -->
                <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                <!-- Dark Logo icon -->
                <!-- <img src="../../assets/images/logo-text.png" alt="homepage" class="light-logo" /> -->
                <!-- </b> -->
                <!--End Logo icon -->
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                <!-- ============================================================== -->
                <!-- create new -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="d-none d-md-block">Create New <i class="fa fa-angle-down"></i></span>
                        <span class="d-block d-md-none"><i class="fa fa-plus"></i></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                <li class="nav-item search-box">
                    <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                    <form class="app-search position-absolute">
                        <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="mdi mdi-bell font-24"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="font-24 mdi mdi-comment-processing"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown" aria-labelledby="2">
                        <ul class="list-style-none">
                            <li>
                                <div class="">
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-success btn-circle"><i class="ti-calendar"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Event today</h5>
                                                <span class="mail-desc">Just a reminder that event</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-info btn-circle"><i class="ti-settings"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Settings</h5>
                                                <span class="mail-desc">You can customize this template</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-primary btn-circle"><i class="ti-user"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Pavan kumar</h5>
                                                <span class="mail-desc">Just see the my admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-danger btn-circle"><i class="fa fa-link"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Luanch Admin</h5>
                                                <span class="mail-desc">Just see the my new admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="../../assets/images/users/1.jpg" alt="user" class="rounded-circle" width="31"></a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated">
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user m-r-5 m-l-5"></i> My Profile</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet m-r-5 m-l-5"></i> My Balance</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-email m-r-5 m-l-5"></i> Inbox</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-settings m-r-5 m-l-5"></i> Account Setting</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                        <div class="dropdown-divider"></div>
                        <div class="p-l-30 p-10"><a href="javascript:void(0)" class="btn btn-sm btn-success btn-rounded">View Profile</a></div>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>

PropertyPosting/Views/Administrator/Layout/_Sidebar.cshtml
 <!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="p-t-30">
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                    <i class="mdi mdi-receipt"></i><span class="hide-menu">Posts </span></a>
                    <ul aria-expanded="false" class="collapse  first-level">
                        <li class="sidebar-item">
                            <a href="@Url.Action("","PostLand")" class="sidebar-link">
                                <i class="mdi mdi-note-outline"></i><span class="hide-menu"> Land </span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="form-wizard.html" class="sidebar-link">
                                <i class="mdi mdi-note-plus"></i><span class="hide-menu"> Home </span>
                            </a>
                        </li>
                    </ul>
                </li>
               
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->