PropertyPosting/Controllers/ApiControllers/PostTypeController.cs
using System.Collections.Generic;
using System.Web.Http;
using AutoMapper;
using PropertyPosting.Controllers.Base;
using PropertyPosting.Controllers.ViewModels.ApiViewModels.PostType.Request;
using PropertyPosting.Controllers.ViewModels.ApiViewModels.PostType.Response;
using PropertyPosting.Models.Domains;
using PropertyPosting.Models.Repository;

namespace PropertyPosting.Controllers.ApiControllers
{
    public class PostTypeController : BaseApiController<PostTypeApiRequest>
    {
        private readonly IRepository<PostType> _postTypeService;
        private readonly IMapper _mapper;

        public PostTypeController(IMapper mapper, IRepository<PostType> postTypeService) : base(mapper)
        {
            _mapper = mapper;
            _postTypeService = postTypeService;
        }

        public override IHttpActionResult Get()
        {
            var postTypes = _postTypeService.GetAll();
            var result = _mapper.Map<IEnumerable<PostTypeApiResponse>>(postTypes);
            return Json(result);
        }

        public override IHttpActionResult Get(long id)
        {
            var postType = _postTypeService.GetById(id);
            if (postType == null)
                return NotFound();
            else
                return Json(_mapper.Map<PostTypeApiResponse>(postType));
        }

        public override IHttpActionResult Post(PostTypeApiRequest t)
        {
            var postType = _mapper.Map<PostType>(t);
            _postTypeService.Insert(postType);
            return Json(postType);
        }

        public override IHttpActionResult Put(long id, PostTypeApiRequest t)
        {
            var postType = _mapper.Map<PostType>(t);
            postType.Id = (int) id;
            _postTypeService.Update(postType);
            return Json(postType);
        }

        public override IHttpActionResult Delete(long id)
        {
            var postType = _postTypeService.GetById(id);
            if (postType == null)
                return NotFound();
            _postTypeService.Delete(postType);
            return Ok();
        }
    }
}

PropertyPosting/Controllers/MvcControllers/Administrator/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PropertyPosting.Controllers.Base;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class HomeController : BaseController
    {
        public HomeController(IMapper mapper) : base(mapper)
        {
        }

        public override ActionResult Index()
        {
            return View("~/Views/Administrator/Home/Index.cshtml");
        }

        public ActionResult PostHome()
        {
            return View();
        }
        public override ActionResult Details(long id)
        {
            throw new NotImplementedException();
        }
    }
}

PropertyPosting/Controllers/MvcControllers/Administrator/PostEntertainmentController.cs
using AutoMapper;
using PropertyPosting.Controllers.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class PostEntertainmentController : BaseController
    {
        public PostEntertainmentController(IMapper mapper) :base(mapper)
        {

        }
        public override ActionResult Details(long id)
        {
            throw new NotImplementedException();
        }


        public override ActionResult Index()
        {
            return View();
        }
    }
}

PropertyPosting/Controllers/MvcControllers/Administrator/PostLandController.cs
using AutoMapper;
using PropertyPosting.Controllers.Base;
using System.Web.Mvc;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class PostLandController : BaseController
    {
        private readonly IMapper _mapper;
        public PostLandController(IMapper mapper): base(mapper)
        {
            _mapper = mapper;
        }
        public override ActionResult Details(long id)
        {

            return View();
        }

        public ActionResult Create()
        {

            return View();
        }

        public override ActionResult Index()
        {
            return View();
        }
    }
}

PropertyPosting/Controllers/MvcControllers/Administrator/PostTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PropertyPosting.Controllers.Base;
using PropertyPosting.Models.Domains;
using PropertyPosting.Models.Repository;

namespace PropertyPosting.Controllers.MvcControllers.Administrator
{
    public class PostTypeController : BaseController
    {
        private readonly IRepository<PostType> _postTypeService;
        private readonly IMapper _mapper;

        public PostTypeController(IMapper mapper, IRepository<PostType> postTypeService) : base(mapper)
        {
            _mapper = mapper;
            _postTypeService = postTypeService;
        }

        public override ActionResult Index()
        {
            var postTypes = _postTypeService.GetAll();
            return View("~/Views/Administrator/PostType/Index.cshtml", postTypes);
        }

        public ActionResult Add()
        {
            return View("~/Views/Administrator/PostType/Create.cshtml");
        }

        [HttpPost]
        public ActionResult Add(PostType postType)
        {
            ModelState.Remove("Id");
            if (!ModelState.IsValid)
                return View("~/Views/Administrator/PostType/Create.cshtml", postType);

            if (postType.Id > 0)
            {
                var postTypeUpdate = _mapper.Map<PostType>(postType);
                _postTypeService.Update(postTypeUpdate);
            }
            else
            {
                _postTypeService.Insert(postType);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var postType = _postTypeService.GetById(id);
            if (postType != null)
            {
                _postTypeService.Delete(postType);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var postType = _postTypeService.GetById(id);
            return View("~/Views/Administrator/PostType/Create.cshtml", postType);
        }

        public override ActionResult Details(long id)
        {
            throw new NotImplementedException();
        }
    }
}

PropertyPosting/Views/Administrator/PostType/Create.cshtml
@using System.Web.Mvc.Html
@model PropertyPosting.Models.Domains.PostType

@{
    Layout = "~/Views/Administrator/Layout/AdministratorLayout.cshtml";
}

<h2>Post type</h2>

@using (Html.BeginForm("Add", "PostType", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(p => p.Id)

    @Html.LabelFor(p => p.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <br />
    @Html.EditorFor(p => p.Name, new { htmlAttributes = new { @class = "form-control" } })
    <br />
    @Html.ValidationMessageFor(p => p.Name, "", new { @class = "text-danger" })

    <br />
    @Html.LabelFor(p => p.Other, htmlAttributes: new { @class = "control-label col-md-2" })
    <br />
    @Html.EditorFor(p => p.Other, new { htmlAttributes = new { @class = "form-control" } })
    <br />
    @Html.ValidationMessageFor(p => p.Other, "", new { @class = "text-danger" })

    <br />
    <input type="submit" value="Create" class="btn btn-default" />

}

<br /><br />
@Html.ActionLink("Back", "Index", "PostType")

PropertyPosting/Views/Administrator/PostType/Index.cshtml
@using System.Web.Mvc.Html
@model IEnumerable<PropertyPosting.Models.Domains.PostType>

@{
    Layout = "~/Views/Administrator/Layout/AdministratorLayout.cshtml";
}

<h2>Post type</h2>

<br /><br />
@Html.ActionLink("[Back]", "Index", "Home")
@Html.ActionLink("[Add]", "Add", "PostType")

<br /><br />
<hr />
<table border="1" width="100%" style="border: 1px solid black; border-collapse: collapse;">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Other</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @{
        foreach (var postType in Model)
        {
            <tr>
                <td>@postType.Id</td>
                <td>@postType.Name</td>
                <td>@postType.Other</td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "PostType", new {id = postType.Id}, null)
                    @Ajax.ActionLink("Edit", "Edit", "PostType", new { id = postType.Id }, new AjaxOptions { HttpMethod = "POST" })
                </td>
            </tr>
        }
    }
    </tbody>
</table>